name: www.yourwebsite.com
services:
    nginx:
        container_name: www.yourwebsite.com
        ports:
            - 80:8080
            - 443:443
        volumes:
            - ./html:/var/www/html:ro
            - ./config:/var/www/config:ro
        image: addohm/nginx-php8-msmtp:latest
