name: cave dive club
services:
    nginx:
        container_name: cdc.addohm.net
        ports:
            - 80:8080
            - 443:443
        volumes:
            - /home/addohm/cdc/v2/:/var/www/html:ro
            - /home/addohm/cdc/v2/config:/var/www/config:ro
        image: addohm/nginx-php8-msmtp:latest
